api_platform:
    title: Hello API Platform
    version: 1.0.0
    
    # This controls Resource endpoints (e.g., /api/users)
    formats:
        jsonld: ['application/ld+json']
        json:   ['application/json']
        html:   ['text/html']

    # This controls the Entrypoint and Docs (e.g., /api)
    docs_formats:
        jsonld: ['application/ld+json']
        json:   ['application/json']
        html:   ['text/html']

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']