framework:
    cache:
        # Redis adapter using Predis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            user.cache:
                adapter: cache.adapter.redis
                default_lifetime: '%env(int:USER_CACHE_TTL)%'
                provider: '%env(REDIS_URL)%'
            
            user.list.cache:
                adapter: cache.adapter.redis
                default_lifetime: '%env(int:USER_LIST_CACHE_TTL)%'
                provider: '%env(REDIS_URL)%'
            
            analytics.cache:
                adapter: cache.adapter.redis
                default_lifetime: '%env(int:ANALYTICS_CACHE_TTL)%'
                provider: '%env(REDIS_URL)%'